/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Posttest3;

/**
 *
 * @author asus
 */
public class Output1 extends javax.swing.JFrame {

    /**
     * Creates new form Output
     */
    public Output1() {
        initComponents();
    }
public Output1(String Nama, String Tempat, String Tanggal, String jk, String Alamat, String Rt, String Rw, String Kel, String Kec, 
        String Kota, String Status, String Golongan, String Pekerjaan, String Kwn, String Agama ) {
        initComponents();
        iNama.setText(Nama);
        iTempat.setText(Tempat);
        iTgl.setText(Tanggal);
        iAlamat.setText(Alamat);
        iRt.setText(Rt);
        iRw.setText(Rw);
        iKel.setText(Kel);
        iKec.setText(Kec);
        iKota.setText(Kota);
        
        iJk.setText(""+jk);
        iKwn.setText(""+Kwn);
        
        iStatus.setText(""+Status);
        iAgama.setText(""+Agama);
        iGol.setText(""+Golongan);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        jPanel3 = new javax.swing.JPanel();
        jNama = new javax.swing.JLabel();
        jTtl = new javax.swing.JLabel();
        jJk = new javax.swing.JLabel();
        jAlamat = new javax.swing.JLabel();
        jKel = new javax.swing.JLabel();
        jRt = new javax.swing.JLabel();
        jKec = new javax.swing.JLabel();
        jAgama = new javax.swing.JLabel();
        jKota = new javax.swing.JLabel();
        jStatus = new javax.swing.JLabel();
        jGol = new javax.swing.JLabel();
        jPeker = new javax.swing.JLabel();
        jKwn = new javax.swing.JLabel();
        iNama = new javax.swing.JLabel();
        iTempat = new javax.swing.JLabel();
        iTempat1 = new javax.swing.JLabel();
        iTgl = new javax.swing.JLabel();
        iJk = new javax.swing.JLabel();
        iAlamat = new javax.swing.JLabel();
        iRt = new javax.swing.JLabel();
        iKel = new javax.swing.JLabel();
        iKec = new javax.swing.JLabel();
        iKota = new javax.swing.JLabel();
        iAgama = new javax.swing.JLabel();
        iStatus = new javax.swing.JLabel();
        iGol = new javax.swing.JLabel();
        iPkr = new javax.swing.JLabel();
        iKwn = new javax.swing.JLabel();
        iTempat14 = new javax.swing.JLabel();
        iRw = new javax.swing.JLabel();
        bExit = new javax.swing.JButton();

        jLabel1.setText("jLabel1");

        setDefaultCloseOperation(javax.swing.WindowConstants.DO_NOTHING_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(0, 0, 0));

        jPanel3.setBackground(new java.awt.Color(204, 204, 255));
        jPanel3.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Kartu Tanda Penduduk (KTP)", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Harrington", 1, 18))); // NOI18N

        jNama.setFont(new java.awt.Font("Lucida Handwriting", 1, 12)); // NOI18N
        jNama.setText("Nama");

        jTtl.setFont(new java.awt.Font("Lucida Handwriting", 1, 12)); // NOI18N
        jTtl.setText("Tempat/Tanggal Lahir");

        jJk.setFont(new java.awt.Font("Lucida Handwriting", 1, 12)); // NOI18N
        jJk.setText("Jenis Kelamin");

        jAlamat.setFont(new java.awt.Font("Lucida Handwriting", 1, 12)); // NOI18N
        jAlamat.setText("Alamat");

        jKel.setFont(new java.awt.Font("Lucida Handwriting", 1, 12)); // NOI18N
        jKel.setText("Kel/Desa");

        jRt.setFont(new java.awt.Font("Lucida Handwriting", 1, 12)); // NOI18N
        jRt.setText("RT/RW");

        jKec.setFont(new java.awt.Font("Lucida Handwriting", 1, 12)); // NOI18N
        jKec.setText("Kecamatan");

        jAgama.setFont(new java.awt.Font("Lucida Handwriting", 1, 12)); // NOI18N
        jAgama.setText("Agama");

        jKota.setFont(new java.awt.Font("Lucida Handwriting", 1, 12)); // NOI18N
        jKota.setText("Kota");

        jStatus.setFont(new java.awt.Font("Lucida Handwriting", 1, 12)); // NOI18N
        jStatus.setText("Status");

        jGol.setFont(new java.awt.Font("Lucida Handwriting", 1, 12)); // NOI18N
        jGol.setText("Golongan Darah");

        jPeker.setFont(new java.awt.Font("Lucida Handwriting", 1, 12)); // NOI18N
        jPeker.setText("Pekerjaan");

        jKwn.setFont(new java.awt.Font("Lucida Handwriting", 1, 12)); // NOI18N
        jKwn.setText("Kewarganegaraan");

        iNama.setFont(new java.awt.Font("Lucida Handwriting", 1, 12)); // NOI18N
        iNama.setText("Nama");

        iTempat.setFont(new java.awt.Font("Lucida Handwriting", 1, 12)); // NOI18N
        iTempat.setText("Nama");

        iTempat1.setFont(new java.awt.Font("Lucida Handwriting", 1, 12)); // NOI18N
        iTempat1.setText("/");

        iTgl.setFont(new java.awt.Font("Lucida Handwriting", 1, 12)); // NOI18N
        iTgl.setText("Nama");

        iJk.setFont(new java.awt.Font("Lucida Handwriting", 1, 12)); // NOI18N
        iJk.setText("Nama");

        iAlamat.setFont(new java.awt.Font("Lucida Handwriting", 1, 12)); // NOI18N
        iAlamat.setText("Nama");

        iRt.setFont(new java.awt.Font("Lucida Handwriting", 1, 12)); // NOI18N
        iRt.setText("Nama");

        iKel.setFont(new java.awt.Font("Lucida Handwriting", 1, 12)); // NOI18N
        iKel.setText("Nama");

        iKec.setFont(new java.awt.Font("Lucida Handwriting", 1, 12)); // NOI18N
        iKec.setText("Nama");

        iKota.setFont(new java.awt.Font("Lucida Handwriting", 1, 12)); // NOI18N
        iKota.setText("Nama");

        iAgama.setFont(new java.awt.Font("Lucida Handwriting", 1, 12)); // NOI18N
        iAgama.setText("Nama");

        iStatus.setFont(new java.awt.Font("Lucida Handwriting", 1, 12)); // NOI18N
        iStatus.setText("Nama");

        iGol.setFont(new java.awt.Font("Lucida Handwriting", 1, 12)); // NOI18N
        iGol.setText("Nama");

        iPkr.setFont(new java.awt.Font("Lucida Handwriting", 1, 12)); // NOI18N
        iPkr.setText("Nama");

        iKwn.setFont(new java.awt.Font("Lucida Handwriting", 1, 12)); // NOI18N
        iKwn.setText("Nama");

        iTempat14.setFont(new java.awt.Font("Lucida Handwriting", 1, 12)); // NOI18N
        iTempat14.setText("/");

        iRw.setFont(new java.awt.Font("Lucida Handwriting", 1, 12)); // NOI18N
        iRw.setText("Nama");

        bExit.setFont(new java.awt.Font("Segoe UI Symbol", 1, 14)); // NOI18N
        bExit.setText("EXIT");
        bExit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bExitActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jNama)
                            .addComponent(jTtl)
                            .addComponent(jJk)
                            .addComponent(jAlamat)))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGap(64, 64, 64)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jKel)
                            .addComponent(jRt)
                            .addComponent(jKec)
                            .addComponent(jKota)))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jAgama)
                            .addComponent(jStatus)
                            .addComponent(jGol)
                            .addComponent(jPeker)
                            .addComponent(jKwn))))
                .addGap(43, 43, 43)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(iAgama, javax.swing.GroupLayout.PREFERRED_SIZE, 148, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(jPanel3Layout.createSequentialGroup()
                                .addComponent(iRt, javax.swing.GroupLayout.PREFERRED_SIZE, 74, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(iTempat14, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(iRw, javax.swing.GroupLayout.PREFERRED_SIZE, 74, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(iNama, javax.swing.GroupLayout.PREFERRED_SIZE, 268, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(iJk, javax.swing.GroupLayout.PREFERRED_SIZE, 148, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(iKel, javax.swing.GroupLayout.PREFERRED_SIZE, 148, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(iKec, javax.swing.GroupLayout.PREFERRED_SIZE, 148, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(iKota, javax.swing.GroupLayout.PREFERRED_SIZE, 148, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(iStatus, javax.swing.GroupLayout.PREFERRED_SIZE, 148, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(iGol, javax.swing.GroupLayout.PREFERRED_SIZE, 148, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(iPkr, javax.swing.GroupLayout.PREFERRED_SIZE, 148, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(iAlamat, javax.swing.GroupLayout.PREFERRED_SIZE, 201, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addContainerGap(102, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                        .addComponent(iKwn, javax.swing.GroupLayout.PREFERRED_SIZE, 148, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(bExit)
                        .addGap(29, 29, 29))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addComponent(iTempat, javax.swing.GroupLayout.PREFERRED_SIZE, 138, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(iTempat1, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(iTgl, javax.swing.GroupLayout.PREFERRED_SIZE, 146, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE))))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(21, 21, 21)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jNama)
                    .addComponent(iNama))
                .addGap(22, 22, 22)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTtl)
                    .addComponent(iTempat)
                    .addComponent(iTempat1)
                    .addComponent(iTgl))
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGap(28, 28, 28)
                        .addComponent(jJk))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGap(36, 36, 36)
                        .addComponent(iJk)))
                .addGap(18, 18, 18)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jAlamat, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(iAlamat, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(15, 15, 15)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jRt)
                    .addComponent(iRt)
                    .addComponent(iTempat14)
                    .addComponent(iRw))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jKel)
                    .addComponent(iKel))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jKec)
                    .addComponent(iKec))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jKota)
                    .addComponent(iKota))
                .addGap(10, 10, 10)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jAgama)
                    .addComponent(iAgama))
                .addGap(18, 18, 18)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jStatus)
                    .addComponent(iStatus))
                .addGap(18, 18, 18)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jGol)
                    .addComponent(iGol))
                .addGap(18, 18, 18)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jPeker)
                    .addComponent(iPkr))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jKwn)
                    .addComponent(iKwn)
                    .addComponent(bExit))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void bExitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bExitActionPerformed
        // TODO add your handling code here:
        this.dispose();
    }//GEN-LAST:event_bExitActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Output1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Output1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Output1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Output1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Output1().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton bExit;
    private javax.swing.JLabel iAgama;
    private javax.swing.JLabel iAlamat;
    private javax.swing.JLabel iGol;
    private javax.swing.JLabel iJk;
    private javax.swing.JLabel iKec;
    private javax.swing.JLabel iKel;
    private javax.swing.JLabel iKota;
    private javax.swing.JLabel iKwn;
    private javax.swing.JLabel iNama;
    private javax.swing.JLabel iPkr;
    private javax.swing.JLabel iRt;
    private javax.swing.JLabel iRw;
    private javax.swing.JLabel iStatus;
    private javax.swing.JLabel iTempat;
    private javax.swing.JLabel iTempat1;
    private javax.swing.JLabel iTempat14;
    private javax.swing.JLabel iTgl;
    private javax.swing.JLabel jAgama;
    private javax.swing.JLabel jAlamat;
    private javax.swing.JLabel jGol;
    private javax.swing.JLabel jJk;
    private javax.swing.JLabel jKec;
    private javax.swing.JLabel jKel;
    private javax.swing.JLabel jKota;
    private javax.swing.JLabel jKwn;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jNama;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JLabel jPeker;
    private javax.swing.JLabel jRt;
    private javax.swing.JLabel jStatus;
    private javax.swing.JLabel jTtl;
    // End of variables declaration//GEN-END:variables
}
