/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Tugas3;

/**
 *
 * @author ACER.DX
 */
public class Posttest3 extends javax.swing.JFrame {

    /**
     * Creates new form Posttest3
     */
    public Posttest3() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jk = new javax.swing.ButtonGroup();
        kwn = new javax.swing.ButtonGroup();
        konten = new javax.swing.JPanel();
        apHome = new javax.swing.JPanel();
        jLabel6 = new javax.swing.JLabel();
        jLabel36 = new javax.swing.JLabel();
        pForm_ktp = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jNama = new javax.swing.JLabel();
        jTtl = new javax.swing.JLabel();
        jJk = new javax.swing.JLabel();
        jAlamat = new javax.swing.JLabel();
        jRt = new javax.swing.JLabel();
        jKel = new javax.swing.JLabel();
        jKec = new javax.swing.JLabel();
        jKota = new javax.swing.JLabel();
        jAgama = new javax.swing.JLabel();
        jStatus = new javax.swing.JLabel();
        jGol = new javax.swing.JLabel();
        jPkrj = new javax.swing.JLabel();
        jWna = new javax.swing.JLabel();
        txtNama = new javax.swing.JTextField();
        txtTempat = new javax.swing.JTextField();
        txtTgl = new javax.swing.JTextField();
        jLabel16 = new javax.swing.JLabel();
        rPr = new javax.swing.JRadioButton();
        rLk = new javax.swing.JRadioButton();
        txtAlamat = new javax.swing.JTextField();
        txtRt = new javax.swing.JTextField();
        txtRw = new javax.swing.JTextField();
        jLabel17 = new javax.swing.JLabel();
        txtKel = new javax.swing.JTextField();
        txtKec = new javax.swing.JTextField();
        txtKota = new javax.swing.JTextField();
        cbAgama = new javax.swing.JComboBox();
        cbStatus = new javax.swing.JComboBox();
        cbGol = new javax.swing.JComboBox();
        txtPekerjaan = new javax.swing.JTextField();
        rWni = new javax.swing.JRadioButton();
        rWna = new javax.swing.JRadioButton();
        bRegister = new javax.swing.JButton();
        Reset = new javax.swing.JButton();
        jLabel5 = new javax.swing.JLabel();
        Profil = new javax.swing.JPanel();
        jLabel7 = new javax.swing.JLabel();
        jLabel18 = new javax.swing.JLabel();
        jLabel19 = new javax.swing.JLabel();
        jLabel20 = new javax.swing.JLabel();
        jLabel21 = new javax.swing.JLabel();
        jLabel22 = new javax.swing.JLabel();
        jLabel23 = new javax.swing.JLabel();
        jLabel24 = new javax.swing.JLabel();
        jLabel25 = new javax.swing.JLabel();
        jLabel26 = new javax.swing.JLabel();
        jLabel27 = new javax.swing.JLabel();
        jLabel28 = new javax.swing.JLabel();
        jLabel29 = new javax.swing.JLabel();
        Sejarah1 = new javax.swing.JPanel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        jLabel30 = new javax.swing.JLabel();
        jLabel31 = new javax.swing.JLabel();
        jLabel32 = new javax.swing.JLabel();
        jLabel33 = new javax.swing.JLabel();
        jLabel34 = new javax.swing.JLabel();
        jLabel35 = new javax.swing.JLabel();
        Header = new javax.swing.JPanel();
        logo = new javax.swing.JLabel();
        kantor = new javax.swing.JLabel();
        jl = new javax.swing.JLabel();
        kota = new javax.swing.JLabel();
        post = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        Home = new usu.widget.ButtonGlass();
        profil = new usu.widget.ButtonGlass();
        Sejarah = new usu.widget.ButtonGlass();
        form_ktp = new usu.widget.ButtonGlass();
        Exit = new usu.widget.ButtonGlass();
        jLabel37 = new javax.swing.JLabel();
        footer = new javax.swing.JPanel();
        Cpright = new javax.swing.JLabel();
        Right_Sidebar = new javax.swing.JPanel();
        fotoKP = new javax.swing.JLabel();
        thursday = new javax.swing.JLabel();
        Wednesday = new javax.swing.JLabel();
        Thuesday = new javax.swing.JLabel();
        monday = new javax.swing.JLabel();
        OHours = new javax.swing.JLabel();
        saturday = new javax.swing.JLabel();
        sunday = new javax.swing.JLabel();
        friday = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        Left_sidebar = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DO_NOTHING_ON_CLOSE);

        konten.setBackground(new java.awt.Color(0, 0, 102));
        konten.setLayout(new java.awt.CardLayout());

        apHome.setBackground(new java.awt.Color(0, 0, 153));

        jLabel6.setIcon(new javax.swing.ImageIcon("C:\\Users\\ACER.DX\\Pictures\\visual\\15.JPG")); // NOI18N

        jLabel36.setFont(new java.awt.Font("Segoe Script", 1, 18)); // NOI18N
        jLabel36.setForeground(new java.awt.Color(255, 255, 255));
        jLabel36.setText("SELAMAT DATANG DI PT PERSERO POS LOA JANAN ILIR");

        javax.swing.GroupLayout apHomeLayout = new javax.swing.GroupLayout(apHome);
        apHome.setLayout(apHomeLayout);
        apHomeLayout.setHorizontalGroup(
            apHomeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(apHomeLayout.createSequentialGroup()
                .addContainerGap(142, Short.MAX_VALUE)
                .addGroup(apHomeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, apHomeLayout.createSequentialGroup()
                        .addComponent(jLabel36)
                        .addGap(140, 140, 140))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, apHomeLayout.createSequentialGroup()
                        .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 583, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(127, 127, 127))))
        );
        apHomeLayout.setVerticalGroup(
            apHomeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(apHomeLayout.createSequentialGroup()
                .addGap(49, 49, 49)
                .addComponent(jLabel36)
                .addGap(44, 44, 44)
                .addComponent(jLabel6)
                .addContainerGap(198, Short.MAX_VALUE))
        );

        konten.add(apHome, "card6");

        pForm_ktp.setBackground(new java.awt.Color(255, 204, 153));

        jPanel2.setBackground(new java.awt.Color(255, 204, 153));
        jPanel2.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "FORM ISIAN", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Serif", 1, 18), new java.awt.Color(255, 255, 255))); // NOI18N

        jNama.setFont(new java.awt.Font("SimSun-ExtB", 1, 14)); // NOI18N
        jNama.setText("Nama");

        jTtl.setFont(new java.awt.Font("SimSun-ExtB", 1, 14)); // NOI18N
        jTtl.setText("Tempat/Tanggal Lahir");

        jJk.setFont(new java.awt.Font("SimSun-ExtB", 1, 14)); // NOI18N
        jJk.setText("Jenis Kelamin");

        jAlamat.setFont(new java.awt.Font("SimSun-ExtB", 1, 14)); // NOI18N
        jAlamat.setText("Alamat");

        jRt.setFont(new java.awt.Font("SimSun-ExtB", 1, 14)); // NOI18N
        jRt.setText("RT/RW");

        jKel.setFont(new java.awt.Font("SimSun-ExtB", 1, 14)); // NOI18N
        jKel.setText("Kel/Desa");

        jKec.setFont(new java.awt.Font("SimSun-ExtB", 1, 14)); // NOI18N
        jKec.setText("Kecamatan");

        jKota.setFont(new java.awt.Font("SimSun-ExtB", 1, 14)); // NOI18N
        jKota.setText("Kota");

        jAgama.setFont(new java.awt.Font("SimSun-ExtB", 1, 14)); // NOI18N
        jAgama.setText("Agama");

        jStatus.setFont(new java.awt.Font("SimSun-ExtB", 1, 14)); // NOI18N
        jStatus.setText("Status");

        jGol.setFont(new java.awt.Font("SimSun-ExtB", 1, 14)); // NOI18N
        jGol.setText("Golongan Darah");

        jPkrj.setFont(new java.awt.Font("SimSun-ExtB", 1, 14)); // NOI18N
        jPkrj.setText("Pekerjaan");

        jWna.setFont(new java.awt.Font("SimSun-ExtB", 1, 14)); // NOI18N
        jWna.setText("Kewarganegaraan");

        txtNama.setFont(new java.awt.Font("SimHei", 1, 12)); // NOI18N

        txtTempat.setFont(new java.awt.Font("SimHei", 1, 12)); // NOI18N

        txtTgl.setFont(new java.awt.Font("SimHei", 1, 12)); // NOI18N

        jLabel16.setFont(new java.awt.Font("SimSun-ExtB", 1, 14)); // NOI18N
        jLabel16.setText("/");

        jk.add(rPr);
        rPr.setFont(new java.awt.Font("SimHei", 1, 12)); // NOI18N
        rPr.setText("Perempuan");

        jk.add(rLk);
        rLk.setFont(new java.awt.Font("SimHei", 1, 12)); // NOI18N
        rLk.setText("Laki-Laki");

        txtAlamat.setFont(new java.awt.Font("SimHei", 1, 12)); // NOI18N

        txtRt.setFont(new java.awt.Font("SimHei", 1, 12)); // NOI18N

        txtRw.setFont(new java.awt.Font("SimHei", 1, 12)); // NOI18N

        jLabel17.setFont(new java.awt.Font("SimSun-ExtB", 1, 14)); // NOI18N
        jLabel17.setText("/");

        txtKel.setFont(new java.awt.Font("SimHei", 1, 12)); // NOI18N

        txtKec.setFont(new java.awt.Font("SimHei", 1, 12)); // NOI18N

        txtKota.setFont(new java.awt.Font("SimHei", 1, 12)); // NOI18N

        cbAgama.setFont(new java.awt.Font("SimHei", 1, 12)); // NOI18N
        cbAgama.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Kristen", "Islam", "Budha", "Hindu", "Konghucu" }));

        cbStatus.setFont(new java.awt.Font("SimHei", 1, 12)); // NOI18N
        cbStatus.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Kawin", "Belum Kawin" }));

        cbGol.setFont(new java.awt.Font("SimHei", 1, 12)); // NOI18N
        cbGol.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "A", "O", "AB", "B" }));

        txtPekerjaan.setFont(new java.awt.Font("SimHei", 1, 12)); // NOI18N

        kwn.add(rWni);
        rWni.setFont(new java.awt.Font("SimHei", 1, 12)); // NOI18N
        rWni.setText("WNI");

        kwn.add(rWna);
        rWna.setFont(new java.awt.Font("SimHei", 1, 12)); // NOI18N
        rWna.setText("WNA");

        bRegister.setFont(new java.awt.Font("Sitka Small", 1, 12)); // NOI18N
        bRegister.setText("Register");
        bRegister.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bRegisterActionPerformed(evt);
            }
        });

        Reset.setFont(new java.awt.Font("Sitka Small", 1, 12)); // NOI18N
        Reset.setText("Reset");
        Reset.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ResetActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jJk)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addGap(38, 38, 38)
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jRt)
                                    .addComponent(jKel)
                                    .addComponent(jKec)
                                    .addComponent(jKota)))
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addContainerGap()
                                .addComponent(jAgama)))
                        .addGap(78, 78, 78)
                        .addComponent(cbAgama, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jNama)
                                    .addComponent(jTtl))
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addGroup(jPanel2Layout.createSequentialGroup()
                                        .addGap(17, 17, 17)
                                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                            .addComponent(txtNama, javax.swing.GroupLayout.PREFERRED_SIZE, 247, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                .addComponent(txtAlamat, javax.swing.GroupLayout.PREFERRED_SIZE, 246, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addGroup(jPanel2Layout.createSequentialGroup()
                                                    .addComponent(rPr)
                                                    .addGap(68, 68, 68)
                                                    .addComponent(rLk))
                                                .addGroup(jPanel2Layout.createSequentialGroup()
                                                    .addComponent(txtRt, javax.swing.GroupLayout.PREFERRED_SIZE, 51, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                    .addGap(16, 16, 16)
                                                    .addComponent(jLabel17)
                                                    .addGap(18, 18, 18)
                                                    .addComponent(txtRw, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE))
                                                .addComponent(txtKel, javax.swing.GroupLayout.PREFERRED_SIZE, 191, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addComponent(txtKec, javax.swing.GroupLayout.PREFERRED_SIZE, 191, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addComponent(txtKota, javax.swing.GroupLayout.PREFERRED_SIZE, 191, javax.swing.GroupLayout.PREFERRED_SIZE))))
                                    .addGroup(jPanel2Layout.createSequentialGroup()
                                        .addGap(18, 18, 18)
                                        .addComponent(txtTempat, javax.swing.GroupLayout.PREFERRED_SIZE, 112, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(jLabel16)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(txtTgl, javax.swing.GroupLayout.PREFERRED_SIZE, 112, javax.swing.GroupLayout.PREFERRED_SIZE))))
                            .addComponent(jAlamat))))
                .addGap(33, 33, 33)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jGol)
                            .addComponent(jStatus))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(cbStatus, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(cbGol, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jWna)
                            .addComponent(jPkrj))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addComponent(Reset, javax.swing.GroupLayout.PREFERRED_SIZE, 79, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 74, Short.MAX_VALUE)
                                .addComponent(bRegister))
                            .addComponent(txtPekerjaan, javax.swing.GroupLayout.PREFERRED_SIZE, 224, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addComponent(rWni)
                                .addGap(70, 70, 70)
                                .addComponent(rWna))))))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(txtTgl, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jGol)
                                    .addComponent(cbGol, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(3, 3, 3))
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jNama)
                                    .addComponent(txtNama, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jTtl)
                                    .addComponent(txtTempat, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel16))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED))))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jStatus)
                            .addComponent(cbStatus, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)))
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jJk)
                        .addComponent(rPr))
                    .addComponent(rLk))
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(6, 6, 6)
                        .addComponent(jAlamat))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txtAlamat, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtPekerjaan, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jPkrj))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(jRt)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jWna)
                            .addComponent(rWni)
                            .addComponent(rWna)))
                    .addComponent(txtRw, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txtRt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel17))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jKel)
                            .addComponent(txtKel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addGap(11, 11, 11)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtKec, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jKec))
                .addGap(13, 13, 13)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtKota, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Reset)
                    .addComponent(bRegister)
                    .addComponent(jKota))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jAgama)
                    .addComponent(cbAgama, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(201, Short.MAX_VALUE))
        );

        jLabel5.setFont(new java.awt.Font("Poor Richard", 1, 24)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(153, 153, 153));
        jLabel5.setText("FORM KARTU PENDUDUK");

        javax.swing.GroupLayout pForm_ktpLayout = new javax.swing.GroupLayout(pForm_ktp);
        pForm_ktp.setLayout(pForm_ktpLayout);
        pForm_ktpLayout.setHorizontalGroup(
            pForm_ktpLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pForm_ktpLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(pForm_ktpLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pForm_ktpLayout.createSequentialGroup()
                        .addComponent(jLabel5)
                        .addGap(268, 268, 268))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pForm_ktpLayout.createSequentialGroup()
                        .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap())))
        );
        pForm_ktpLayout.setVerticalGroup(
            pForm_ktpLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pForm_ktpLayout.createSequentialGroup()
                .addComponent(jLabel5)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        konten.add(pForm_ktp, "card3");

        Profil.setBackground(new java.awt.Color(255, 204, 102));

        jLabel7.setFont(new java.awt.Font("Comic Sans MS", 1, 24)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(255, 255, 255));
        jLabel7.setText("PROFIL");

        jLabel18.setIcon(new javax.swing.ImageIcon("C:\\Users\\ACER.DX\\Pictures\\visual\\9.JPG")); // NOI18N

        jLabel19.setFont(new java.awt.Font("Comic Sans MS", 1, 48)); // NOI18N
        jLabel19.setForeground(new java.awt.Color(255, 255, 255));
        jLabel19.setText("|");

        jLabel20.setFont(new java.awt.Font("Comic Sans MS", 1, 10)); // NOI18N
        jLabel20.setForeground(new java.awt.Color(255, 255, 255));
        jLabel20.setText("1906 Perubahan nama Kantor Pos menjadi Posts Telegraaf end Telefoon Diensts");

        jLabel21.setFont(new java.awt.Font("Comic Sans MS", 1, 12)); // NOI18N
        jLabel21.setForeground(new java.awt.Color(255, 255, 255));
        jLabel21.setText("1746 Kantor Pos pertama di Indonesia didirikan di Batavia");

        jLabel22.setFont(new java.awt.Font("Comic Sans MS", 1, 12)); // NOI18N
        jLabel22.setForeground(new java.awt.Color(255, 255, 255));
        jLabel22.setText("1995 Perum Pos dan Giro berubah menjadi PT Pos Indonesia (Persero)");

        jLabel23.setFont(new java.awt.Font("Comic Sans MS", 1, 10)); // NOI18N
        jLabel23.setForeground(new java.awt.Color(255, 255, 255));
        jLabel23.setText("1945 Posts Telegraaf end Telefoon Diensts berubah menjadi Pos Telehraph and Telephone");

        jLabel24.setIcon(new javax.swing.ImageIcon("C:\\Users\\ACER.DX\\Pictures\\visual\\12.JPG")); // NOI18N

        jLabel25.setIcon(new javax.swing.ImageIcon("C:\\Users\\ACER.DX\\Pictures\\visual\\13.JPG")); // NOI18N

        jLabel26.setFont(new java.awt.Font("Comic Sans MS", 1, 18)); // NOI18N
        jLabel26.setForeground(new java.awt.Color(255, 255, 255));
        jLabel26.setText("Presentasi");

        jLabel27.setFont(new java.awt.Font("Comic Sans MS", 1, 18)); // NOI18N
        jLabel27.setForeground(new java.awt.Color(255, 255, 255));
        jLabel27.setText("First ->");

        jLabel28.setIcon(new javax.swing.ImageIcon("C:\\Users\\ACER.DX\\Pictures\\visual\\14.JPG")); // NOI18N

        jLabel29.setFont(new java.awt.Font("Comic Sans MS", 1, 18)); // NOI18N
        jLabel29.setForeground(new java.awt.Color(255, 255, 255));
        jLabel29.setText("<-Now");

        javax.swing.GroupLayout ProfilLayout = new javax.swing.GroupLayout(Profil);
        Profil.setLayout(ProfilLayout);
        ProfilLayout.setHorizontalGroup(
            ProfilLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(ProfilLayout.createSequentialGroup()
                .addGroup(ProfilLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(ProfilLayout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jLabel18)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel7)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel19)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(ProfilLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel23)
                            .addComponent(jLabel21)
                            .addComponent(jLabel20)
                            .addComponent(jLabel22)))
                    .addGroup(ProfilLayout.createSequentialGroup()
                        .addGap(4, 4, 4)
                        .addComponent(jLabel26)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel24)
                        .addGap(18, 18, 18)
                        .addGroup(ProfilLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(ProfilLayout.createSequentialGroup()
                                .addGap(0, 0, Short.MAX_VALUE)
                                .addComponent(jLabel27)
                                .addGap(54, 54, 54)
                                .addComponent(jLabel25))
                            .addGroup(ProfilLayout.createSequentialGroup()
                                .addComponent(jLabel28)
                                .addGap(27, 27, 27)
                                .addComponent(jLabel29)))))
                .addContainerGap())
        );
        ProfilLayout.setVerticalGroup(
            ProfilLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(ProfilLayout.createSequentialGroup()
                .addGroup(ProfilLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(ProfilLayout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jLabel18))
                    .addGroup(ProfilLayout.createSequentialGroup()
                        .addGap(23, 23, 23)
                        .addGroup(ProfilLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel7)
                            .addComponent(jLabel19)))
                    .addGroup(ProfilLayout.createSequentialGroup()
                        .addGap(17, 17, 17)
                        .addComponent(jLabel21)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel20)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel23)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel22)))
                .addGroup(ProfilLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(ProfilLayout.createSequentialGroup()
                        .addGap(39, 39, 39)
                        .addComponent(jLabel24))
                    .addGroup(ProfilLayout.createSequentialGroup()
                        .addGroup(ProfilLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(ProfilLayout.createSequentialGroup()
                                .addGap(18, 18, 18)
                                .addComponent(jLabel25))
                            .addGroup(ProfilLayout.createSequentialGroup()
                                .addGap(132, 132, 132)
                                .addComponent(jLabel26))
                            .addGroup(ProfilLayout.createSequentialGroup()
                                .addGap(50, 50, 50)
                                .addComponent(jLabel27)))
                        .addGroup(ProfilLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(ProfilLayout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jLabel28))
                            .addGroup(ProfilLayout.createSequentialGroup()
                                .addGap(74, 74, 74)
                                .addComponent(jLabel29)))))
                .addContainerGap(176, Short.MAX_VALUE))
        );

        konten.add(Profil, "card5");

        jLabel8.setIcon(new javax.swing.ImageIcon("C:\\Users\\ACER.DX\\Pictures\\visual\\6.JPG")); // NOI18N

        jLabel9.setBackground(new java.awt.Color(255, 153, 0));
        jLabel9.setFont(new java.awt.Font("Gabriola", 1, 14)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(255, 153, 51));
        jLabel9.setText("Sejarah mencatat keberadaan Pos Indonesia begitu panjang, Kantorpos pertama didirikan di Batavia (sekarang Jakarta)");

        jLabel10.setIcon(new javax.swing.ImageIcon("C:\\Users\\ACER.DX\\Pictures\\visual\\7.JPG")); // NOI18N

        jLabel11.setBackground(new java.awt.Color(255, 153, 0));
        jLabel11.setFont(new java.awt.Font("Gabriola", 1, 18)); // NOI18N
        jLabel11.setForeground(new java.awt.Color(255, 153, 51));
        jLabel11.setText("1875 - POSTEN TELEGRAFDIENST");

        jLabel12.setBackground(new java.awt.Color(255, 153, 0));
        jLabel12.setFont(new java.awt.Font("Gabriola", 1, 14)); // NOI18N
        jLabel12.setForeground(new java.awt.Color(255, 153, 51));
        jLabel12.setText("surat penduduk, terutama bagi mereka yang berdagang dari kantor-kantor di luar Jawa dan bagi mereka yang datang dari dan pergi");

        jLabel13.setBackground(new java.awt.Color(255, 153, 0));
        jLabel13.setFont(new java.awt.Font("Gabriola", 1, 14)); // NOI18N
        jLabel13.setForeground(new java.awt.Color(255, 153, 51));
        jLabel13.setText("oleh Gubernur Jenderal G.W Baron van Imhoff pada tanggal 26 Agustus 1746 dengan tujuan untuk lebih menjamin keamanan surat-");

        jLabel14.setBackground(new java.awt.Color(255, 153, 0));
        jLabel14.setFont(new java.awt.Font("Gabriola", 1, 14)); // NOI18N
        jLabel14.setForeground(new java.awt.Color(255, 153, 51));
        jLabel14.setText("ke Negeri Belanda. Sejak itulah pelayanan pos telah lahir mengembang peran dan fungsi pelayanan kepada publik..");

        jLabel15.setIcon(new javax.swing.ImageIcon("C:\\Users\\ACER.DX\\Pictures\\visual\\7.JPG")); // NOI18N

        jLabel30.setBackground(new java.awt.Color(255, 153, 0));
        jLabel30.setFont(new java.awt.Font("Gabriola", 1, 18)); // NOI18N
        jLabel30.setForeground(new java.awt.Color(255, 153, 51));
        jLabel30.setText("1746 - KANTORPOS PERTAMA");

        jLabel31.setBackground(new java.awt.Color(255, 153, 0));
        jLabel31.setFont(new java.awt.Font("Gabriola", 1, 14)); // NOI18N
        jLabel31.setForeground(new java.awt.Color(255, 153, 51));
        jLabel31.setText("Pada tahun ini dinas pos disatukan dengan dinas telegrap dengan status jawatan dengan nama POSTEN TELEGRAFDIENST.");

        jLabel32.setIcon(new javax.swing.ImageIcon("C:\\Users\\ACER.DX\\Pictures\\visual\\7.JPG")); // NOI18N

        jLabel33.setBackground(new java.awt.Color(255, 153, 0));
        jLabel33.setFont(new java.awt.Font("Gabriola", 1, 18)); // NOI18N
        jLabel33.setForeground(new java.awt.Color(255, 153, 51));
        jLabel33.setText("1875 - POSTEN TELEGRAFDIENST");

        jLabel34.setBackground(new java.awt.Color(255, 153, 0));
        jLabel34.setFont(new java.awt.Font("Gabriola", 1, 14)); // NOI18N
        jLabel34.setForeground(new java.awt.Color(255, 153, 51));
        jLabel34.setText("Sejak pemerintahan kolonial dinas pos pemerintahan Belanda sudah berhubungan dalam pengiriman surat dan barang ");

        jLabel35.setBackground(new java.awt.Color(255, 153, 0));
        jLabel35.setFont(new java.awt.Font("Gabriola", 1, 14)); // NOI18N
        jLabel35.setForeground(new java.awt.Color(255, 153, 51));
        jLabel35.setText(" secara internasional, sehingga tercatat sebagai anggota Union Postale Universelle (UPU).");

        javax.swing.GroupLayout Sejarah1Layout = new javax.swing.GroupLayout(Sejarah1);
        Sejarah1.setLayout(Sejarah1Layout);
        Sejarah1Layout.setHorizontalGroup(
            Sejarah1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(Sejarah1Layout.createSequentialGroup()
                .addGroup(Sejarah1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(Sejarah1Layout.createSequentialGroup()
                        .addGap(170, 170, 170)
                        .addComponent(jLabel8))
                    .addGroup(Sejarah1Layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(Sejarah1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel13)
                            .addGroup(Sejarah1Layout.createSequentialGroup()
                                .addComponent(jLabel10)
                                .addGap(18, 18, 18)
                                .addGroup(Sejarah1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel30)
                                    .addComponent(jLabel9)))))
                    .addGroup(Sejarah1Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jLabel12))
                    .addGroup(Sejarah1Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jLabel14))
                    .addGroup(Sejarah1Layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(Sejarah1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel15)
                            .addComponent(jLabel32))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(Sejarah1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel33)
                            .addComponent(jLabel11)
                            .addGroup(Sejarah1Layout.createSequentialGroup()
                                .addGap(10, 10, 10)
                                .addComponent(jLabel31))))
                    .addGroup(Sejarah1Layout.createSequentialGroup()
                        .addGap(60, 60, 60)
                        .addComponent(jLabel34))
                    .addGroup(Sejarah1Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jLabel35)))
                .addContainerGap())
        );
        Sejarah1Layout.setVerticalGroup(
            Sejarah1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(Sejarah1Layout.createSequentialGroup()
                .addComponent(jLabel8)
                .addGap(11, 11, 11)
                .addGroup(Sejarah1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel10)
                    .addGroup(Sejarah1Layout.createSequentialGroup()
                        .addComponent(jLabel30)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel9)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel13)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel12)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel14)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(Sejarah1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(Sejarah1Layout.createSequentialGroup()
                        .addComponent(jLabel11)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel31)
                        .addGap(18, 18, 18)
                        .addComponent(jLabel33))
                    .addGroup(Sejarah1Layout.createSequentialGroup()
                        .addComponent(jLabel15)
                        .addGap(51, 51, 51)
                        .addComponent(jLabel32)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel34)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel35)
                .addContainerGap())
        );

        konten.add(Sejarah1, "card6");

        getContentPane().add(konten, java.awt.BorderLayout.CENTER);

        Header.setBackground(new java.awt.Color(255, 153, 51));
        Header.setBorder(javax.swing.BorderFactory.createEtchedBorder(javax.swing.border.EtchedBorder.RAISED));

        logo.setIcon(new javax.swing.ImageIcon("C:\\Users\\ACER.DX\\Pictures\\visual\\2.JPG")); // NOI18N

        kantor.setFont(new java.awt.Font("Rod", 1, 24)); // NOI18N
        kantor.setForeground(new java.awt.Color(255, 255, 255));
        kantor.setText("Kantor Pos Loa Janan");

        jl.setFont(new java.awt.Font("Rod", 1, 12)); // NOI18N
        jl.setText("Jl. Soekarno - Hatta, Simpang Tiga, Kec. Loa Janan Ilir");

        kota.setFont(new java.awt.Font("Rod", 1, 12)); // NOI18N
        kota.setText("Kota Samarinda, Kalimantan Timur 75391");

        post.setFont(new java.awt.Font("Rod", 1, 12)); // NOI18N
        post.setForeground(new java.awt.Color(255, 255, 255));
        post.setText("Post Office, Finance, Point Of Interest, Establishment");

        jPanel1.setBackground(new java.awt.Color(255, 153, 51));
        jPanel1.setLayout(new java.awt.GridLayout(1, 0));

        Home.setText("HOME");
        Home.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                HomeActionPerformed(evt);
            }
        });
        jPanel1.add(Home);

        profil.setText("PROFIL");
        profil.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                profilActionPerformed(evt);
            }
        });
        jPanel1.add(profil);

        Sejarah.setText("SEJARAH");
        Sejarah.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SejarahActionPerformed(evt);
            }
        });
        jPanel1.add(Sejarah);

        form_ktp.setText("FORM KTP");
        form_ktp.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                form_ktpActionPerformed(evt);
            }
        });
        jPanel1.add(form_ktp);

        Exit.setText("EXIT");
        Exit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ExitActionPerformed(evt);
            }
        });
        jPanel1.add(Exit);

        javax.swing.GroupLayout HeaderLayout = new javax.swing.GroupLayout(Header);
        Header.setLayout(HeaderLayout);
        HeaderLayout.setHorizontalGroup(
            HeaderLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(HeaderLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(logo)
                .addGap(18, 18, 18)
                .addGroup(HeaderLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jl)
                    .addComponent(kota)
                    .addComponent(post)
                    .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(HeaderLayout.createSequentialGroup()
                        .addComponent(kantor)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel37)))
                .addContainerGap())
        );
        HeaderLayout.setVerticalGroup(
            HeaderLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, HeaderLayout.createSequentialGroup()
                .addGroup(HeaderLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(HeaderLayout.createSequentialGroup()
                        .addGroup(HeaderLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(HeaderLayout.createSequentialGroup()
                                .addGap(38, 38, 38)
                                .addComponent(kantor))
                            .addGroup(HeaderLayout.createSequentialGroup()
                                .addGap(61, 61, 61)
                                .addComponent(jLabel37)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jl)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(kota)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(post)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(logo, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );

        getContentPane().add(Header, java.awt.BorderLayout.PAGE_START);

        footer.setBackground(new java.awt.Color(255, 153, 51));

        Cpright.setFont(new java.awt.Font("Segoe Print", 0, 11)); // NOI18N
        Cpright.setForeground(new java.awt.Color(255, 255, 255));
        Cpright.setText("Copyright © 2016 - 2017");

        javax.swing.GroupLayout footerLayout = new javax.swing.GroupLayout(footer);
        footer.setLayout(footerLayout);
        footerLayout.setHorizontalGroup(
            footerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, footerLayout.createSequentialGroup()
                .addContainerGap(582, Short.MAX_VALUE)
                .addComponent(Cpright)
                .addGap(520, 520, 520))
        );
        footerLayout.setVerticalGroup(
            footerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(footerLayout.createSequentialGroup()
                .addGap(26, 26, 26)
                .addComponent(Cpright)
                .addContainerGap(60, Short.MAX_VALUE))
        );

        getContentPane().add(footer, java.awt.BorderLayout.PAGE_END);

        Right_Sidebar.setBackground(new java.awt.Color(204, 204, 204));

        fotoKP.setIcon(new javax.swing.ImageIcon("C:\\Users\\ACER.DX\\Pictures\\visual\\4.JPG")); // NOI18N

        thursday.setFont(new java.awt.Font("Malgun Gothic", 1, 11)); // NOI18N
        thursday.setText("Thursday : 8:00am-3:00pm");

        Wednesday.setFont(new java.awt.Font("Malgun Gothic", 1, 11)); // NOI18N
        Wednesday.setText("Wednesday : 8:00am-3:00pm");

        Thuesday.setFont(new java.awt.Font("Malgun Gothic", 1, 11)); // NOI18N
        Thuesday.setText("Tuesday : 8:00am-3:00pm");

        monday.setFont(new java.awt.Font("Malgun Gothic", 1, 11)); // NOI18N
        monday.setText("Monday : 8:00am-3:00pm");

        OHours.setFont(new java.awt.Font("Malgun Gothic", 1, 12)); // NOI18N
        OHours.setText("Opening Hours :");

        saturday.setFont(new java.awt.Font("Malgun Gothic", 1, 11)); // NOI18N
        saturday.setText("Saturday : 8:00am-3:00pm");

        sunday.setFont(new java.awt.Font("Malgun Gothic", 1, 11)); // NOI18N
        sunday.setText("Sunday : 8:00am-3:00pm");

        friday.setFont(new java.awt.Font("Malgun Gothic", 1, 11)); // NOI18N
        friday.setText("Friday : 8:00am-3:00pm");

        jLabel4.setIcon(new javax.swing.ImageIcon("C:\\Users\\ACER.DX\\Pictures\\visual\\16.JPG")); // NOI18N

        javax.swing.GroupLayout Right_SidebarLayout = new javax.swing.GroupLayout(Right_Sidebar);
        Right_Sidebar.setLayout(Right_SidebarLayout);
        Right_SidebarLayout.setHorizontalGroup(
            Right_SidebarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(Right_SidebarLayout.createSequentialGroup()
                .addGroup(Right_SidebarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(Right_SidebarLayout.createSequentialGroup()
                        .addGap(53, 53, 53)
                        .addComponent(OHours))
                    .addGroup(Right_SidebarLayout.createSequentialGroup()
                        .addGap(29, 29, 29)
                        .addGroup(Right_SidebarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(fotoKP)
                            .addGroup(Right_SidebarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(Thuesday)
                                .addComponent(monday)
                                .addComponent(Wednesday)
                                .addComponent(thursday)
                                .addComponent(friday)
                                .addComponent(saturday)
                                .addComponent(sunday)))))
                .addGap(0, 0, Short.MAX_VALUE))
            .addGroup(Right_SidebarLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 207, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        Right_SidebarLayout.setVerticalGroup(
            Right_SidebarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(Right_SidebarLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(fotoKP)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(OHours)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(monday)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(Thuesday)
                .addGap(8, 8, 8)
                .addComponent(Wednesday)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(thursday)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(friday)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(saturday)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(sunday)
                .addGap(18, 18, 18)
                .addComponent(jLabel4)
                .addContainerGap(137, Short.MAX_VALUE))
        );

        getContentPane().add(Right_Sidebar, java.awt.BorderLayout.LINE_END);

        Left_sidebar.setBackground(new java.awt.Color(204, 204, 204));

        jLabel1.setIcon(new javax.swing.ImageIcon("C:\\Users\\ACER.DX\\Pictures\\visual\\10.JPG")); // NOI18N

        jLabel2.setIcon(new javax.swing.ImageIcon("C:\\Users\\ACER.DX\\Pictures\\visual\\11.JPG")); // NOI18N

        jLabel3.setIcon(new javax.swing.ImageIcon("C:\\Users\\ACER.DX\\Pictures\\visual\\8.JPG")); // NOI18N

        javax.swing.GroupLayout Left_sidebarLayout = new javax.swing.GroupLayout(Left_sidebar);
        Left_sidebar.setLayout(Left_sidebarLayout);
        Left_sidebarLayout.setHorizontalGroup(
            Left_sidebarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(Left_sidebarLayout.createSequentialGroup()
                .addGap(1, 1, 1)
                .addComponent(jLabel1))
            .addComponent(jLabel3)
            .addComponent(jLabel2)
        );
        Left_sidebarLayout.setVerticalGroup(
            Left_sidebarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(Left_sidebarLayout.createSequentialGroup()
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel2)
                .addGap(0, 153, Short.MAX_VALUE))
        );

        getContentPane().add(Left_sidebar, java.awt.BorderLayout.LINE_START);

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void bRegisterActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bRegisterActionPerformed
       //pada source code di bawah ini memberikan keluaran hasil inputan dari jframe posttest3 pada panel pForm_ktp
        //ke Jfame Output1
        String Nama = txtNama.getText();
        String Tempat = txtTempat.getText();
        String Tanggal = txtTgl.getText();
        String Alamat = txtAlamat.getText();
        String Rt = txtRw.getText();
        String Rw = txtRt.getText();
        String Kel = txtKel.getText();
        String Kec = txtKec.getText();
        String Kota = txtKota.getText();
        String Pekerjaan = txtPekerjaan.getText();

        String Agama = cbAgama.getSelectedItem().toString();
        String Status = cbStatus.getSelectedItem().toString();
        String Gol = cbGol.getSelectedItem().toString();

        String jk = null;
        if(rLk.isSelected())
        jk = rLk.getText();
        else if(rLk.isSelected())
        jk = rLk.getText();
        else if(rPr.isSelected())
        jk = rPr.getText();

        String Kwn = null;
        if(rWna.isSelected())
        jk = rWna.getText();
        else if(rWna.isSelected())
        jk = rWna.getText();
        else if(rWni.isSelected())
        jk = rWni.getText();

        Output1 output = new Output1 (Nama,Tempat,Tanggal,jk,Alamat,Rt,Rw,Kel,Kec,Kota,Agama,Status,Gol,Pekerjaan,Kwn);
        output.setVisible(true);
    }//GEN-LAST:event_bRegisterActionPerformed

    private void ResetActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ResetActionPerformed
        // Source code di bawah ini mengarah pada tombol Reset dimana form yang telah di isi dapat di hapus(di kembalikan sepeti
        //semula dengan hanya mengklik tombol reset
        txtNama.setText("");
        txtAlamat.setText("");
        txtTempat.setText("");
        txtTgl.setText("");
        txtRw.setText("");
        txtRt.setText("");
        txtKec.setText("");
        txtKel.setText("");
        txtKota.setText("");
        txtPekerjaan.setText("");

        jk.clearSelection();
        kwn.clearSelection();

        cbGol.setSelectedItem(null);
        cbAgama.setSelectedItem(null);
        cbStatus.setSelectedItem(null);
    }//GEN-LAST:event_ResetActionPerformed

    private void HomeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_HomeActionPerformed
        // pada source code di bawah ini dengan memberi nilai  true ketika mengklik tombol Home 
        //secara otomatis teralih ke panel Home karna panel apHome di beri nilai True
        apHome.setVisible(true);
        Profil.setVisible(false);
        Sejarah1.setVisible(false);
        pForm_ktp.setVisible(false);
    }//GEN-LAST:event_HomeActionPerformed

    private void profilActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_profilActionPerformed
       // pada source code di bawah ini dengan memberi nilai  true ketika mengklik tombol Profil 
        //secara otomatis teralih ke panel Profil karna panel Profil di beri nilai True
        Profil.setVisible(true);
        apHome.setVisible(false);
        Sejarah1.setVisible(false);
        pForm_ktp.setVisible(false);
    }//GEN-LAST:event_profilActionPerformed

    private void SejarahActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SejarahActionPerformed
        // pada source code di bawah ini dengan memberi nilai  true ketika mengklik tombol Sejarah1 
        //secara otomatis teralih ke panel Sejarah1 karna panel Sejarah1 di beri nilai True
        Sejarah1.setVisible(true);
        apHome.setVisible(false);
        Profil.setVisible(false);
        pForm_ktp.setVisible(false);
    }//GEN-LAST:event_SejarahActionPerformed

    private void form_ktpActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_form_ktpActionPerformed
        // pada source code di bawah ini dengan memberi nilai  true ketika mengklik tombol pForm_ktp 
        //secara otomatis teralih ke panel pForm_ktp karna panel pForm_ktp di beri nilai True
        pForm_ktp.setVisible(true);
        apHome.setVisible(false);
        Sejarah1.setVisible(false);
        Profil.setVisible(false);
    }//GEN-LAST:event_form_ktpActionPerformed

    private void ExitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ExitActionPerformed
        //dengan system.exit(0); memberikan progam jframe keluar(berhenti)
        System.exit(0);
    }//GEN-LAST:event_ExitActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Posttest3.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Posttest3.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Posttest3.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Posttest3.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Posttest3().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel Cpright;
    private usu.widget.ButtonGlass Exit;
    private javax.swing.JPanel Header;
    private usu.widget.ButtonGlass Home;
    private javax.swing.JPanel Left_sidebar;
    private javax.swing.JLabel OHours;
    private javax.swing.JPanel Profil;
    private javax.swing.JButton Reset;
    private javax.swing.JPanel Right_Sidebar;
    private usu.widget.ButtonGlass Sejarah;
    private javax.swing.JPanel Sejarah1;
    private javax.swing.JLabel Thuesday;
    private javax.swing.JLabel Wednesday;
    private javax.swing.JPanel apHome;
    private javax.swing.JButton bRegister;
    private javax.swing.JComboBox cbAgama;
    private javax.swing.JComboBox cbGol;
    private javax.swing.JComboBox cbStatus;
    private javax.swing.JPanel footer;
    private usu.widget.ButtonGlass form_ktp;
    private javax.swing.JLabel fotoKP;
    private javax.swing.JLabel friday;
    private javax.swing.JLabel jAgama;
    private javax.swing.JLabel jAlamat;
    private javax.swing.JLabel jGol;
    private javax.swing.JLabel jJk;
    private javax.swing.JLabel jKec;
    private javax.swing.JLabel jKel;
    private javax.swing.JLabel jKota;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel23;
    private javax.swing.JLabel jLabel24;
    private javax.swing.JLabel jLabel25;
    private javax.swing.JLabel jLabel26;
    private javax.swing.JLabel jLabel27;
    private javax.swing.JLabel jLabel28;
    private javax.swing.JLabel jLabel29;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel30;
    private javax.swing.JLabel jLabel31;
    private javax.swing.JLabel jLabel32;
    private javax.swing.JLabel jLabel33;
    private javax.swing.JLabel jLabel34;
    private javax.swing.JLabel jLabel35;
    private javax.swing.JLabel jLabel36;
    private javax.swing.JLabel jLabel37;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JLabel jNama;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JLabel jPkrj;
    private javax.swing.JLabel jRt;
    private javax.swing.JLabel jStatus;
    private javax.swing.JLabel jTtl;
    private javax.swing.JLabel jWna;
    private javax.swing.ButtonGroup jk;
    private javax.swing.JLabel jl;
    private javax.swing.JLabel kantor;
    private javax.swing.JPanel konten;
    private javax.swing.JLabel kota;
    private javax.swing.ButtonGroup kwn;
    private javax.swing.JLabel logo;
    private javax.swing.JLabel monday;
    private javax.swing.JPanel pForm_ktp;
    private javax.swing.JLabel post;
    private usu.widget.ButtonGlass profil;
    private javax.swing.JRadioButton rLk;
    private javax.swing.JRadioButton rPr;
    private javax.swing.JRadioButton rWna;
    private javax.swing.JRadioButton rWni;
    private javax.swing.JLabel saturday;
    private javax.swing.JLabel sunday;
    private javax.swing.JLabel thursday;
    private javax.swing.JTextField txtAlamat;
    private javax.swing.JTextField txtKec;
    private javax.swing.JTextField txtKel;
    private javax.swing.JTextField txtKota;
    private javax.swing.JTextField txtNama;
    private javax.swing.JTextField txtPekerjaan;
    private javax.swing.JTextField txtRt;
    private javax.swing.JTextField txtRw;
    private javax.swing.JTextField txtTempat;
    private javax.swing.JTextField txtTgl;
    // End of variables declaration//GEN-END:variables
}
